name: "Flatpak Add Remotes"
description: "Add Flatpak remotes to use"
inputs:
  verbose:
    description: "Enable verbosity"
    default: "false"
  remotes:
    description: |
      A list of name-URL pairs of Flatpak remotes to add.
      Members of the pair is separated with a space.
      Check the readme for an example.
    required: true
outputs:
  verbose:
    description: "Verbosity state given as input"
  remotes-names:
    description: |
      Name list of the Flatpak remotes given as input.
      Check the readme for an example.
  first-remote-url:
    description: URL of the first remote of the Flatpak remotes given as input
runs:
  using: "node24"
  main: "../../dist/add-remotes/index.js"
