name: "Flatpak Builder Build And Finish"
description: "Build and finish a Flatpak following its manifest"
inputs:
  verbose:
    description: "Enable verbosity"
    default: "false"
  arch:
    description: |
      Specify the machine architecture to build for (e.g. x86_64, aarch64).
      If no architecture is specified, the host architecture will be automatically detected.
    required: false
  branch:
    description: "Specify the branch to use when finishing the build"
    required: true
  state-dir:
    description: "Use this directory for storing state (downloads, build dirs, build cache, etc) rather than the internal default (.flatpak-builder)"
    required: false
  build-dir:
    description: "Use this directory for storing the build rather than the internal default (builddir)"
    required: false
  manifest-path:
    description: "Path to the Flatpak manifest to build"
    required: true
  ccache:
    description: "Enable use of ccache in the build (needs ccache in the sdk)"
    default: "false"
  stop-at-module:
    description: "Stop at the specified module, ignoring it and all the following ones"
    required: false
  run-tests:
    description: "Run modules tests if any"
    default: "true"
outputs:
  verbose:
    description: "Verbosity state given as input"
  arch:
    description: "Machine architecture specified as input"
  branch:
    description: "Branch given as input"
  state-dir:
    description: "State directory used"
  build-dir:
    description: "Build directory used"
  manifest-path:
    description: "Path to the Flatpak manifest given as input"
runs:
  using: "node24"
  main: "../../dist/build-and-finish/index.js"
