name: "Flatpak Builder"
description: "Build and create a bundle from a Flatpak manifest"
inputs:
  verbose:
    description: "Enable verbosity"
    default: "false"
  remotes:
    description: |
      A list of name-URL pairs of Flatpak remotes to add.
      Members of the pair is separated with a space.
      Check the readme for an example.
    required: true
runs:
  using: "node24"
  main: "../dist/build-full/index.js"
