on:
  push:
  pull_request:

name: Tests
env:
  # NOTE: Flathub Beta is added just to have two remotes
  REMOTES: |
    flathub https://flathub.org/repo/flathub.flatpakrepo
    flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
jobs:
  build-step-by-step:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
    steps:
      - uses: actions/checkout@v6

      - name: Add remotes
        uses: ./flatpak-builder/add-remotes
        with:
          verbose: true
          remotes: ${{ env.REMOTES }}

  build-full:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
    steps:
      - uses: actions/checkout@v6

      - uses: ./flatpak-builder
        with:
          verbose: true
          remotes: ${{ env.REMOTES }}
