on:
  push:
  pull_request:

name: Tests
env:
  # NOTE: Flathub Beta is added just to have two remotes
  REMOTES: |
    flathub https://flathub.org/repo/flathub.flatpakrepo
    flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
  MANIFEST_PATH: ./.github/flatpaks/gtk3-project/org.example.TestApp.Devel.yml
  BRANCH: ci-test
  COMMIT_SUBJECT: Initial commit
  MIRROR_SCREENSHOTS_URL: https://example.com/media
  BUNDLE_NAME: TestApp
jobs:
  build-step-by-step:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
      - uses: actions/checkout@v6

      - name: Add remotes
        id: add_remotes
        uses: ./flatpak/add-remotes
        with:
          verbose: true
          remotes: ${{ env.REMOTES }}

      - name: Install dependencies
        id: install_deps
        uses: ./flatpak-builder/install-deps
        with:
          verbose: ${{ steps.add_remotes.outputs.verbose }}
          install-deps-from: ${{ steps.add_remotes.outputs.remotes-names }}
          manifest-path: ${{ env.MANIFEST_PATH }}

      - name: Check state directory (${{ steps.install_deps.outputs.state-dir }})
        uses: ./.github/actions/test-check-state-dir
        with:
          state-dir: ${{ steps.install_deps.outputs.state-dir }}
          ccache-exist: false

      - name: Download sources
        id: download_sources
        uses: ./flatpak-builder/download-sources
        with:
          verbose: ${{ steps.install_deps.outputs.verbose }}
          arch: ${{ steps.install_deps.outputs.arch }}
          state-dir: ${{ steps.install_deps.outputs.state-dir }}
          manifest-path: ${{ steps.install_deps.outputs.manifest-path }}

      - name: Check state directory (${{ steps.download_sources.outputs.state-dir }})
        uses: ./.github/actions/test-check-state-dir
        with:
          state-dir: ${{ steps.download_sources.outputs.state-dir }}
          ccache-exist: false

      - name: Build and finish
        id: build_and_finish
        uses: ./flatpak-builder/build-and-finish
        with:
          verbose: ${{ steps.download_sources.outputs.verbose }}
          arch: ${{ steps.download_sources.outputs.arch }}
          branch: ${{ env.BRANCH }}
          state-dir: ${{ steps.download_sources.outputs.state-dir }}
          manifest-path: ${{ steps.download_sources.outputs.manifest-path }}

      - name: Re-download sources (ccache check)
        id: re_download_sources
        uses: ./flatpak-builder/download-sources
        with:
          verbose: false
          arch: ${{ steps.build_and_finish.outputs.arch }}
          state-dir: ${{ steps.build_and_finish.outputs.state-dir }}
          manifest-path: ${{ steps.build_and_finish.outputs.manifest-path }}

      - name: Check state directory (${{ steps.re_download_sources.outputs.state-dir }})
        uses: ./.github/actions/test-check-state-dir
        with:
          state-dir: ${{ steps.re_download_sources.outputs.state-dir }}
          ccache-exist: true
      
      - name: Export build
        id: export_build
        uses: ./flatpak-builder/export-build
        with:
          verbose: ${{ steps.build_and_finish.outputs.verbose }}
          arch: ${{ steps.build_and_finish.outputs.arch }}
          branch: ${{ steps.build_and_finish.outputs.branch }}
          state-dir: ${{ steps.build_and_finish.outputs.state-dir }}
          build-dir: ${{ steps.build_and_finish.outputs.build-dir }}
          manifest-path: ${{ steps.build_and_finish.outputs.manifest-path }}
          commit-subject: ${{ env.COMMIT_SUBJECT }}
          mirror-screenshots-url: ${{ env.MIRROR_SCREENSHOTS_URL }}

      - name: Bundle
        uses: ./flatpak/bundle
        with:
          verbose: ${{ steps.export_build.outputs.verbose }}
          arch: ${{ steps.export_build.outputs.arch }}
          branch: ${{ steps.export_build.outputs.branch }}
          repo-dir: ${{ steps.export_build.outputs.repo-dir }}
          runtime-repo: ${{ steps.add_remotes.outputs.first-remote-url }}
          bundle-name: ${{ env.BUNDLE_NAME }}
          id: ${{ steps.export_build.outputs.manifest-id }}

  build-full:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
      - uses: actions/checkout@v6

      - uses: ./flatpak-builder
        with:
          verbose: true
          remotes: ${{ env.REMOTES }}
          branch: ${{ env.BRANCH }}
          manifest-path: ${{ env.MANIFEST_PATH }}
          commit-subject: ${{ env.COMMIT_SUBJECT }}
          mirror-screenshots-url: ${{ env.MIRROR_SCREENSHOTS_URL }}
          bundle-name: ${{ env.BUNDLE_NAME }}

  flat-manager:
    runs-on: ubuntu-latest
    services:
      db:
        image: docker.io/library/postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db

    container:
      image: ghcr.io/flatpak/flat-manager:latest
    steps:
      - uses: actions/checkout@v6

      - name: Create flat-manager instance
        id: manager
        working-directory: ./.github/flat-manager
        env:
          DATABASE_URL: postgres://postgres:postgres@db/test_db
        run: |
          mkdir build-repo
          ostree --repo=repo init --mode=archive-z2
          (flat-manager 2>&1 | tee ./flat-manager.log) &

      - run: |
          flat-manager-client --print-output gentoken --secret=secret --repo=stable

      - run: |
          echo "REPO_TOKEN=$(flat-manager-client gentoken --secret=secret --repo=stable)" | tee -a $GITHUB_ENV
      - run: |
          flat-manager-client --print-output create http://127.0.0.1:8080 stable
      
      - run: |
          flat-manager-client --help

      - name: Print flat-manager instance log
        if: ${{ steps.manager.conclusion == 'success' && (success() || failure()) }}
        working-directory: ./.github/flat-manager
        run: |
          cat ./flat-manager.log
